// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhZWSXASOTJek2xed3We0rur20JrCDVEM',
    appId: '1:29245156115:web:701fbcb1dc0d8b8109c8e6',
    messagingSenderId: '29245156115',
    projectId: 'events-c16',
    authDomain: 'events-c16.firebaseapp.com',
    storageBucket: 'events-c16.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfx7Rx06_OHDsaOrI83m0_RBpVGP4Ar40',
    appId: '1:29245156115:android:b3d4625aabacb68009c8e6',
    messagingSenderId: '29245156115',
    projectId: 'events-c16',
    storageBucket: 'events-c16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2-m8xZueVkXV2T7huZ6q3JfaPRAq1pWc',
    appId: '1:29245156115:ios:75b4411b243ab29a09c8e6',
    messagingSenderId: '29245156115',
    projectId: 'events-c16',
    storageBucket: 'events-c16.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2-m8xZueVkXV2T7huZ6q3JfaPRAq1pWc',
    appId: '1:29245156115:ios:75b4411b243ab29a09c8e6',
    messagingSenderId: '29245156115',
    projectId: 'events-c16',
    storageBucket: 'events-c16.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhZWSXASOTJek2xed3We0rur20JrCDVEM',
    appId: '1:29245156115:web:88046877f0f198d109c8e6',
    messagingSenderId: '29245156115',
    projectId: 'events-c16',
    authDomain: 'events-c16.firebaseapp.com',
    storageBucket: 'events-c16.firebasestorage.app',
  );

}